//! Provenance tracking for macro expansion.
//!
//! This module provides types to track the origin of syntax nodes through
//! macro expansion and compiler transformations. This is the **pre-desugar
//! provenance bridge** - a minimal model that preserves origin information
//! before a full AST → HIR lowering exists.
//!
//! # Purpose
//!
//! Provenance tracking enables:
//!
//! - **Diagnostics**: Error messages point to macro call sites, not expanded code
//! - **Tooling**: LSP go-to-definition, hover, and other features work in expanded code
//! - **Debugging**: Understanding how generated code maps to source
//! - **Future HIR**: Foundation for AST → HIR lowering with source origins
//!
//! # Architecture
//!
//! The design is intentionally minimal: a span-based mapping that works with
//! the existing AST without requiring node-level provenance attachment. This
//! "v1 bridge" approach allows us to track origins without redesigning the
//! entire AST.
//!
//! ## Components
//!
//! - **`Provenance`**: Enum tracking where a node came from
//!   - `DirectSource`: Directly from source file
//!   - `ExpandedFrom`: Generated by macro expansion
//!   - `SyntheticFor`: Compiler-generated (e.g., hygiene renames)
//!
//! - **`ProvenanceMap`**: Maps spans to their provenance
//!   - Span-based for compatibility with existing AST
//!   - BTreeMap for deterministic iteration
//!   - File-scoped for context
//!
//! - **`Provenanced<T>`**: Wrapper for AST nodes with provenance
//!   - Alternative to span-based mapping
//!   - Useful for future node-level attachment
//!
//! # Usage Flow
//!
//! 1. **During Expansion**: As macros are expanded, record provenance for each
//!    expanded node with its origin information.
//!
//! 2. **For Diagnostics**: When reporting errors, look up provenance to point
//!    to the original source location instead of expanded code locations.
//!
//! 3. **For Tooling**: LSP and other tools can trace expanded code back to
//!    macro definitions and call sites.
//!
//! 4. **Future HIR**: During AST → HIR lowering, attach provenance to HIR nodes
//!    to maintain origin information through compilation phases.

use crate::frontend::ast::Span;
use crate::frontend::diagnostics::FileSpan;
use crate::frontend::source::FileId;
use std::collections::BTreeMap;

/// Tracks the origin of syntax nodes through macro expansion and compiler transformations.
///
/// This is the "pre-desugar provenance bridge" - a minimal model that preserves
/// origin information without requiring full AST redesign.
///
/// # Examples
///
/// ```ignore
/// // Direct source code
/// Provenance::DirectSource { file_id, span }
///
/// // Generated by macro expansion
/// Provenance::ExpandedFrom {
///     macro_name: "unless".to_string(),
///     call_site_file: file_id,
///     call_site_span: macro_invocation_span,
///     definition_span: Some(macro_definition_span),
/// }
///
/// // Compiler-generated for hygiene
/// Provenance::SyntheticFor {
///     purpose: SynthesisPurpose::HygieneRename,
///     related_span: Some((file_id, original_span)),
/// }
/// ```
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Provenance {
    /// Directly from source file - no expansion involved.
    ///
    /// This is the default provenance for all code that wasn't generated
    /// by macros or compiler transformations.
    DirectSource {
        /// The file this code came from
        file_id: FileId,
        /// The span in the source file
        span: Span,
    },

    /// Generated by macro expansion.
    ///
    /// Tracks both where the macro was invoked (for error reporting) and
    /// optionally where in the macro definition the expansion came from.
    ExpandedFrom {
        /// Name of the macro that generated this node
        macro_name: String,
        /// File where the macro was invoked
        call_site_file: FileId,
        /// Span of the macro invocation in source
        call_site_span: Span,
        /// Optional: span in the macro definition template
        definition_span: Option<Span>,
    },

    /// Synthesized by the compiler (not from macro expansion).
    ///
    /// Used for compiler-generated code like temporary wrappers, desugared
    /// constructs, or hygiene-generated identifiers.
    SyntheticFor {
        /// Purpose of this synthesized code
        purpose: SynthesisPurpose,
        /// Related source location (if applicable)
        related_span: Option<(FileId, Span)>,
    },
}

/// The purpose of compiler-synthesized code.
///
/// Helps distinguish between different kinds of compiler-generated code
/// for better diagnostics and debugging.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SynthesisPurpose {
    /// Desugaring of language constructs
    Desugar,

    /// Hygiene-driven identifier renaming
    HygieneRename,

    /// Temporary wrapper for compilation
    TemporaryWrapper,

    /// Other compiler-generated code
    Other(String),
}

impl std::fmt::Display for SynthesisPurpose {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Desugar => write!(f, "desugaring"),
            Self::HygieneRename => write!(f, "hygiene rename"),
            Self::TemporaryWrapper => write!(f, "temporary wrapper"),
            Self::Other(s) => write!(f, "{}", s),
        }
    }
}

/// AST node with provenance information.
///
/// This mirrors `Spanned<T>` but tracks origin through expansions.
/// Unlike spans, provenance is preserved through transformations.
///
/// # Example
///
/// ```ignore
/// let expr = Provenanced::new(
///     some_expr_node,
///     Provenance::ExpandedFrom { ... }
/// );
/// ```
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Provenanced<T> {
    /// The underlying AST node
    pub node: T,
    /// Where this node came from
    pub provenance: Provenance,
}

impl<T> Provenanced<T> {
    /// Creates a new provenanced node.
    #[must_use]
    pub const fn new(node: T, provenance: Provenance) -> Self {
        Self { node, provenance }
    }

    /// Creates a DirectSource provenance from a FileSpan.
    #[must_use]
    pub fn from_file_span(node: T, file_span: FileSpan) -> Self {
        Self {
            node,
            provenance: Provenance::DirectSource {
                file_id: file_span.file_id,
                span: file_span.span,
            },
        }
    }

    /// Maps the inner node using a function.
    ///
    /// This preserves the provenance information.
    #[must_use]
    pub fn map<U, F>(self, f: F) -> Provenanced<U>
    where
        F: FnOnce(T) -> U,
    {
        Provenanced {
            node: f(self.node),
            provenance: self.provenance,
        }
    }
}

/// Maps spans in an expanded AST to their provenance.
///
/// Uses BTreeMap for deterministic iteration and ordered lookups.
/// The map is keyed by span in the expanded AST, allowing us to look up
/// where any expanded node originally came from.
///
/// # Design Notes
///
/// - **Span-based keys**: Spans are stable after parsing, making them reliable keys
/// - **BTreeMap**: Provides deterministic iteration order for reproducible behavior
/// - **File association**: Each map is tied to a specific file_id for context
/// - **No Default**: Intentionally requires explicit file_id to prevent silent bugs
///
/// # Example
///
/// ```ignore
/// let mut map = ProvenanceMap::new(file_id);
///
/// // Record that this span came from a macro expansion
/// map.insert(expanded_span, Provenance::ExpandedFrom {
///     macro_name: "unless".to_string(),
///     call_site_file: file_id,
///     call_site_span: macro_call_span,
///     definition_span: Some(template_span),
/// });
///
/// // Later, look up where this span came from
/// if let Some(prov) = map.get(span) {
///     match prov {
///         Provenance::ExpandedFrom { call_site_span, .. } => {
///             // Report error at macro call site instead of in expanded code
///         }
///         _ => {}
///     }
/// }
/// ```
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProvenanceMap {
    /// Map from span to provenance
    map: BTreeMap<Span, Provenance>,

    /// Track which file_id spans belong to (needed for lookups)
    file_id: FileId,
}

impl ProvenanceMap {
    /// Creates a new provenance map for the given file.
    #[must_use]
    pub const fn new(file_id: FileId) -> Self {
        Self {
            map: BTreeMap::new(),
            file_id,
        }
    }

    /// Returns the file_id this map is associated with.
    #[must_use]
    pub const fn file_id(&self) -> FileId {
        self.file_id
    }

    /// Record provenance for a span.
    ///
    /// If the span already has provenance recorded, it will be replaced.
    pub fn insert(&mut self, span: Span, provenance: Provenance) {
        self.map.insert(span, provenance);
    }

    /// Look up provenance for an exact span.
    ///
    /// Returns `None` if no provenance is recorded for this exact span.
    #[must_use]
    pub fn get(&self, span: Span) -> Option<&Provenance> {
        self.map.get(&span)
    }

    /// Find the smallest span containing this offset.
    ///
    /// This is useful for finding provenance of a node when you only have
    /// a byte offset within the expanded file.
    ///
    /// # Example
    ///
    /// ```ignore
    /// // Find what generated the code at byte offset 1234
    /// if let Some(prov) = map.find_containing(1234) {
    ///     println!("Code at offset 1234 came from: {:?}", prov);
    /// }
    /// ```
    #[must_use]
    pub fn find_containing(&self, offset: usize) -> Option<&Provenance> {
        self.map
            .iter()
            .find(|(span, _)| span.start <= offset && offset <= span.end)
            .map(|(_, prov)| prov)
    }

    /// Iterate over all span-provenance pairs in order.
    ///
    /// Returns pairs in sorted order by span start position.
    pub fn iter(&self) -> impl Iterator<Item = (&Span, &Provenance)> {
        self.map.iter()
    }

    /// Returns the number of provenance entries in this map.
    #[must_use]
    pub fn len(&self) -> usize {
        self.map.len()
    }

    /// Returns true if this map contains no provenance entries.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.map.is_empty()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_provenanced_from_file_span() {
        let file_id = FileId::new(0);
        let span = Span::new(10, 20);
        let file_span = FileSpan::new(file_id, span);

        let prov = Provenanced::from_file_span("test_node", file_span);

        assert!(matches!(
            prov.provenance,
            Provenance::DirectSource { file_id: f, span: s } if f == file_id && s == span
        ));
    }

    #[test]
    fn test_provenanced_map() {
        let prov = Provenanced::new(
            "original",
            Provenance::DirectSource {
                file_id: FileId::new(0),
                span: Span::new(0, 10),
            },
        );

        let mapped = prov.map(|s| format!("{}-modified", s));

        assert_eq!(mapped.node, "original-modified");
        assert!(matches!(mapped.provenance, Provenance::DirectSource { .. }));
    }

    #[test]
    fn test_provenance_map_insert_and_get() {
        let file_id = FileId::new(0);
        let mut map = ProvenanceMap::new(file_id);

        let span = Span::new(10, 20);
        let prov = Provenance::DirectSource { file_id, span };
        map.insert(span, prov.clone());

        assert_eq!(map.get(span), Some(&prov));
    }

    #[test]
    fn test_provenance_map_find_containing() {
        let file_id = FileId::new(0);
        let mut map = ProvenanceMap::new(file_id);

        let span1 = Span::new(10, 20);
        let span2 = Span::new(30, 40);

        map.insert(
            span1,
            Provenance::DirectSource {
                file_id,
                span: span1,
            },
        );
        map.insert(
            span2,
            Provenance::DirectSource {
                file_id,
                span: span2,
            },
        );

        // Offset within span1
        assert_eq!(
            map.find_containing(15),
            Some(&Provenance::DirectSource {
                file_id,
                span: span1
            })
        );

        // Offset within span2
        assert_eq!(
            map.find_containing(35),
            Some(&Provenance::DirectSource {
                file_id,
                span: span2
            })
        );

        // Offset not in any span
        assert_eq!(map.find_containing(25), None);
    }

    #[test]
    fn test_provenance_map_iteration() {
        let file_id = FileId::new(0);
        let mut map = ProvenanceMap::new(file_id);

        let span1 = Span::new(10, 20);
        let span2 = Span::new(30, 40);

        map.insert(
            span2,
            Provenance::DirectSource {
                file_id,
                span: span2,
            },
        );
        map.insert(
            span1,
            Provenance::DirectSource {
                file_id,
                span: span1,
            },
        );

        let spans: Vec<_> = map.iter().map(|(s, _)| *s).collect();
        assert_eq!(spans, vec![span1, span2], "iteration is ordered by span");
    }
}
